### ISSUE TITLE
AxeItemAccessor crash

### ISSUE THREAD

**Issue by TheFruxz** [aleksilassila/litematica-printer#133]
```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2022-09-10 13:43:04
Description: Ticking entity

java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/content/registry/AxeItemAccessor
	at me.aleksilassila.litematica.printer.printer.PlacementGuide.buildAction(PlacementGuide.java:125)
	at me.aleksilassila.litematica.printer.printer.PlacementGuide.getAction(PlacementGuide.java:38)
	at me.aleksilassila.litematica.printer.printer.Printer.tick(Printer.java:101)
	at net.minecraft.class_746.handler$cgi005$tick(class_746.java:3915)
	at net.minecraft.class_746.method_5773(class_746.java:245)
	at net.minecraft.class_638.method_18646(class_638.java:267)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
	at net.minecraft.class_310.method_1574(class_310.java:1851)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.mixin.content.registry.AxeItemAccessor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:159)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 22 more
```

Running on Quilt 1.19.2 - macOS 13.0 Beta (22A5342f) - Apple Silicon / M1 Max

**Comment by patyhank** [comment]
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2022-12-08 11:47:27
Description: Ticking entity

java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/content/registry/AxeItemAccessor
	at me.aleksilassila.litematica.printer.v1_19.guides.interaction.LogStrippingGuide.<clinit>(LogStrippingGuide.java:27)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at me.aleksilassila.litematica.printer.v1_19.guides.Guides.getInteractionGuides(Guides.java:66)
	at me.aleksilassila.litematica.printer.v1_19.Printer.onGameTick(Printer.java:55)
	at net.minecraft.class_746.handler$bho000$tick(class_746.java:2927)
	at net.minecraft.class_746.method_5773(class_746.java:245)
	at net.minecraft.class_638.method_18646(class_638.java:267)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
	at net.minecraft.class_310.method_1574(class_310.java:1851)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.mixin.content.registry.AxeItemAccessor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:159)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 36 more
```
Still Crashed in Quilt 1.19.2
Using QFAPI: qfapi-4.0.0-beta.24_qsl-3.0.0-beta.24_fapi-0.68.0_mc-1.19.2.jar

**Comment by aleksilassila** [comment]
[quilt-patches.zip](https://github.com/aleksilassila/litematica-printer/files/10185003/quilt-patches.zip)
Could someone with Quilt try if this patch fixed the issue?

**Comment by patyhank** [comment]
There is no AxeItemAccessor Class in the Quilt Fabric API

**Comment by aleksilassila** [comment]
#138 We have been bamboozled

**Comment by aleksilassila** [comment]
Actually maybe it should have worked, what kind of error did you get @patyhank, was it identical?

**Comment by patyhank** [comment]
It works
