### ISSUE TITLE
crashiing

### ISSUE THREAD

**Issue by dragondad2** [aleksilassila/litematica-printer#145]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2022-12-11 21:12:40
Description: Ticking entity

java.lang.NoSuchMethodError: 'boolean net.minecraft.class_1799.method_7929(net.minecraft.class_1799)'
	at me.aleksilassila.litematica.printer.v1_19.guides.Guide.getSlotWithItem(Guide.java:38)
	at me.aleksilassila.litematica.printer.v1_19.guides.Guide.getRequiredItem(Guide.java:80)
	at me.aleksilassila.litematica.printer.v1_19.guides.Guide.getStackSlot(Guide.java:51)
	at me.aleksilassila.litematica.printer.v1_19.guides.Guide.playerHasRightItem(Guide.java:31)
	at me.aleksilassila.litematica.printer.v1_19.guides.Guide.canExecute(Guide.java:58)
	at me.aleksilassila.litematica.printer.v1_19.guides.placement.PlacementGuide.canExecute(PlacementGuide.java:68)
	at me.aleksilassila.litematica.printer.v1_19.guides.placement.GuesserGuide.canExecute(GuesserGuide.java:94)
	at me.aleksilassila.litematica.printer.v1_19.Printer.onGameTick(Printer.java:60)
	at net.minecraft.class_746.handler$zki000$tick(class_746.java:1854)
	at net.minecraft.class_746.method_5773(class_746.java:235)
	at net.minecraft.class_638.method_18646(class_638.java:269)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_638.method_32124(class_638.java:252)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:248)
	at net.minecraft.class_310.method_1574(class_310.java:1885)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.aleksilassila.litematica.printer.v1_19.guides.Guide.getSlotWithItem(Guide.java:38)
	at me.aleksilassila.litematica.printer.v1_19.guides.Guide.getRequiredItem(Guide.java:80)
	at me.aleksilassila.litematica.printer.v1_19.guides.Guide.getStackSlot(Guide.java:51)
	at me.aleksilassila.litematica.printer.v1_19.guides.Guide.playerHasRightItem(Guide.java:31)
	at me.aleksilassila.litematica.printer.v1_19.guides.Guide.canExecute(Guide.java:58)
	at me.aleksilassila.litematica.printer.v1_19.guides.placement.PlacementGuide.canExecute(PlacementGuide.java:68)
	at me.aleksilassila.litematica.printer.v1_19.guides.placement.GuesserGuide.canExecute(GuesserGuide.java:94)
	at me.aleksilassila.litematica.printer.v1_19.Printer.onGameTick(Printer.java:60)
	at net.minecraft.class_746.handler$zki000$tick(class_746.java:1854)
	at net.minecraft.class_746.method_5773(class_746.java:235)
	at net.minecraft.class_638.method_18646(class_638.java:269)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_638.method_32124(class_638.java:252)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:248)

**Comment by dragondad2** [comment]
i put in that jar you sent to another 4 days ago i saw it today tried it but it didnt work

**Comment by poepieskatwools** [comment]
I'm haveing the same issue using the following versions:
MC: 1.19.3
Litematica: 1.19.3-0.13.0
Printer: 1.19-3.0
Basically to reproduce it you just load a schematic and try to print. The first block gets placed then the game crashes. In some cases the world gets corrupted and crashes even if you remove the printer. The entity being ticked is the player and what I've seen happen after removing the printer and loading a corrupted world, world edit will tick the player.

Sorry if what I'm describing doesn't make sense but hope this helps you find the problem (if the problem is the printer)

**Comment by dragondad2** [comment]
Yea I just switch back to 1.19.2 versions

**Comment by aleksilassila** [comment]
I'll release a fix tomorrow or the day after

**Comment by aleksilassila** [comment]
This should be now resolved. Please reopen the issue if it still occurs
